### PR TITLE
Add tjong anthony intro md. Fixes #274

### LINKED ISSUE #274: Add TjongAnthony-Intro.md

### PR DESCRIPTION
**Pull request by tjonganthony**
Ready for review.

### CODE REVIEW

**Comment by xdshang** [comment]
Missing 'Fixes' clause.
Better to revise the PR title.
The commit message should be in imperative mood (i.e. ‘add’ rather than ‘adding’ or ‘added’).

**Comment by tjonganthony** [comment]
Fixed xdshang problem.

**Comment by xdshang** [comment]
@tjonganthony where is the 'Fixes {Issue No.}'?

**Comment by tjonganthony** [comment]
It's in the commit message.
Should I add it in the PR tittle?
Done too btw.

**Comment by xdshang** [comment]
It should be in the comment, so that people can click that reference to direct to the issue page.

**Pull request merged**
