### PR TITLE
Add DewiTanJiaHui.txt

### PR DESCRIPTION
**Pull request by jessidew95**
Ready for review

### CODE REVIEW

**Comment by jessidew95** [comment]
Ready for Review

**Comment by xdshang** [comment]
this pr contains an extra file.

**Comment by jessidew95** [comment]
@xdshang May I know which file is the correct file and which is the extra file? 
Sorry for any inconvenience caused.

**Comment by xdshang** [comment]
'users/DewiTanJiaHui-Intro.md' is not supposed to be appeared in this pr......

**Pull request merged**
