### PR TITLE
Add ZhaoDingfan-Intro.md #542

### LINKED ISSUE #542: Add ZhaoDingfan-Intro.md

### PR DESCRIPTION
**Pull request by dfz2019**
Fixes #542

### CODE REVIEW

**Comment by dfz2019** [comment]
Ready for review

**Comment by xdshang** [comment]
please use exactly same personal name for all your file names.
the path of two files is incorrect. they should be in the directory /users

**Comment by dfz2019** [comment]
Dear tutor, which files should have the same personal names?

**Comment by xdshang** [comment]
`{YourName}.txt`  and `{YourName}-Intro.md`, two names should be exactly same.
And both files should be in the dir `/user`

**Comment by dfz2019** [comment]
I don't know how to change the path of the two files so I just add "users/" in front of the name of my file and I don't know whether it works.

**Pull request merged**
