### PR TITLE
Add Advay-Intro.md #476

### LINKED ISSUE #476: Add Advay-Intro.md

### PR DESCRIPTION
**Pull request by advaypal**
Fixes #476

### CODE REVIEW

**Comment by advaypal** [comment]
Ready for Review

**Comment by xdshang** [comment]
@advaypal please using exactly same personal name for all your file names.

**Comment by advaypal** [comment]
@xdshang Are you talking about "advay" vs "Advay"? I'll just rename this one then, or do you have a particular preference?

**Comment by xdshang** [comment]
yes, make them identical.

**Comment by advaypal** [comment]
@xdshang Done

**Pull request merged**
