### PR TITLE
add Murray.txt

### PR DESCRIPTION
**Pull request by mchen14**
Ready for Review

### CODE REVIEW

**Comment by mchen14** [comment]
Add MurrayChen-intro.md #494 is included in here too, interestingly enough.
Fixes #494 .

**Comment by xdshang** [comment]
`{YourName}-Intro.md` should not be included in this pr. 
open a new pr to submit `{YourName}-Intro.md`

**Comment by mchen14** [comment]
when i created a new PR on master it auto merged my previous commits into this one PR, and doesn't give me the option to create a new PR.

**Comment by xdshang** [comment]
maybe you should create a new branch, rather than master

**Comment by mchen14** [comment]
Yeah I did that just now, submitting the intro.md file there. The other pr also has the .txt file in it though, because I didn't pr the first time from there. And the same thing happens there as well now--when i click new pr, it redirects me to the existing one for that branch.

**Pull request merged**
