### PR TITLE
Add to TanWangLeng.txt #8

### LINKED ISSUE #8: Add TanWangLeng-Intro.md

### PR DESCRIPTION
**Pull request by yamgent**
Fixes #8.

### CODE REVIEW

**Comment by damithc** [comment]
@yamgent Need to resolve conflicts. Alternatively, close this one and submit a new PR.

**Comment by yamgent** [comment]
Ok. I will submit a new PR.

**Comment by damithc** [comment]
@yamgent note that we have updated the exercise to prevent this sort of merge conflicts. Please follow the updated instructions.

**Comment by yamgent** [comment]
Noted. Thanks! :smile:

**Pull request closed without merging**
