### PR TITLE
Add ChewZhiJiang-Intro.md #272

### LINKED ISSUE #272: Add ChewZhiJiang-Intro.md

### PR DESCRIPTION
**Pull request by zavfel**
Fixes #272

### CODE REVIEW

**Comment by zavfel** [comment]
Ready for Review

**Comment by xdshang** [comment]
@zavfel please using the exactly same personal name in all your file names.

**Comment by zavfel** [comment]
@xdshang I have updated all files to same name

**Comment by xdshang** [comment]
could you reopen a new pr to submit again? because you submitted `Zhijiang.txt` before, I have to revert this merging.

**Comment by zavfel** [comment]
@xdshang I have submitted a new pr again with the same title

**Comment by xdshang** [comment]
thanks

**Pull request merged**
