### PR TITLE
Add TranVietQuang-Intro.md #200

### LINKED ISSUE #200: Add TranVietQuang-Intro.md

### PR DESCRIPTION
**Pull request by vitquay1996**
Fixes #200
Ready for Review

### CODE REVIEW

**Comment by xdshang** [comment]
please follow the required format of commit message, and the directory to place your files.

**Comment by vitquay1996** [comment]
Fixes #200

**Comment by vitquay1996** [comment]
Ready for review

**Comment by xdshang** [comment]
please remove the files outside the dir /users. and there should be two required files under /users.

**Comment by vitquay1996** [comment]
Fixes #200

**Comment by vitquay1996** [comment]
Ready for review

**Comment by xdshang** [comment]
remove the 2 files outside the /users please. this pr is supposed to contain only 2 files.

**Pull request merged**
