### PR TITLE
Add PhuaKianMing-Intro.md #194

### LINKED ISSUE #194: Add PhuaKianMing-Intro.md

### PR DESCRIPTION
**Pull request by daredevil999**
Fixes #194

### CODE REVIEW

**Comment by daredevil999** [comment]
Ready for review

**Comment by xdshang** [comment]
@daredevil999 please using the exactly same personal name for all your file names.

**Comment by daredevil999** [comment]
Okay, noted Xindi

Sent from Outlookhttp://aka.ms/weboutlook

**Comment by xdshang** [comment]
please correct the file name in this pr too.

**Comment by daredevil999** [comment]
Ready for review

**Pull request merged**
