### PR TITLE
Add TranVietQuang.txt

### PR DESCRIPTION
**Pull request by vitquay1996**
Ready for review

### CODE REVIEW

**Comment by xdshang** [comment]
`{YourName}.txt` is under wrong directory

**Comment by vitquay1996** [comment]
I have fixed that the directory.
Ready for review

**Comment by xdshang** [comment]
please remove the redundant file.

**Comment by vitquay1996** [comment]
Delete redundant file

**Comment by vitquay1996** [comment]
Ready for review

**Pull request merged**
