### PR TITLE
Add DewiTanJiaHui-intro-md

### LINKED ISSUE #243: Add DewiTanJiaHui-Intro.md
Add DewiTanJiaHui-Intro.md

### PR DESCRIPTION
**Pull request by jessidew95**
Fixes #243

### CODE REVIEW

**Comment by xdshang** [comment]
PR title needs to be revised.
You should have consistent name of yourself.

**Comment by xdshang** [comment]
@jessidew95  you also need to use exactly same personal name in all your file names.

**Comment by jessidew95** [comment]
I am having trouble figuring out how to push the DewiTanJiaHui.txt file into this PR

**Comment by jessidew95** [comment]
Okay, fixed it! I hope this is okay!

**Comment by xdshang** [comment]
@jessidew95 Hmm... It seems there are some conflicts to be resolved.

**Pull request merged**
