### PR TITLE
Add ZhiYuan Intro.md #118

### LINKED ISSUE #117: Add ZhiYuan-Intro.md

### PR DESCRIPTION
**Pull request by Zhiyuan-Amos**
Fixes #118

### CODE REVIEW

**Comment by Zhiyuan-Amos** [comment]
Ready For Review

**Comment by xdshang** [comment]
brand naming is in wrong format

**Comment by xdshang** [comment]
File name is incorrect.

**Comment by Zhiyuan-Amos** [comment]
Updated file name!

**Comment by xdshang** [comment]
You just updated the PR title. 
The problem is `Add ZhiYuan-Intro.md.txt` should be `ZhiYuan-Intro.md`. Please commit more to rename that file.

**Pull request closed without merging**
