### PR TITLE
Add hujingrui-Intro.md #593

### LINKED ISSUE #593: Add hujingrui-Intro.md

### PR DESCRIPTION
**Pull request by jingrui-who**
Fixes #593

### CODE REVIEW

**Comment by jingrui-who** [comment]
Ready for review

**Comment by xdshang** [comment]
please keep {YourName} identical and consistent, and delete redundant files.

**Comment by jingrui-who** [comment]
ok sure. i am still learning how to use git at the moment so i wanted to retry the basics. How come i cannot file the 2 files that i added in the user file even though i sent a pull request? Did i do anything wrong?

**Comment by xdshang** [comment]
You have known how to delete a file. This is almost same to change the name of one file.

**Comment by jingrui-who** [comment]
ok thx for the advice. I have just done that. Ready for review.

**Pull request merged**
